# Generated by Django 3.2 on 2021-05-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210505_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('imageone', models.ImageField(blank=True, upload_to='slider/')),
                ('imagetwo', models.ImageField(blank=True, upload_to='slider/')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('bgimage', models.ImageField(blank=True, upload_to='slider/')),
            ],
        ),
    ]
