# Generated by Django 3.2 on 2021-05-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_rightimage_sliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
