# Generated by Django 3.2 on 2021-05-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20210506_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rightimage',
            old_name='imageone',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='rightimage',
            name='imagetwo',
        ),
    ]
