# Generated by Django 3.2 on 2021-05-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
